all: classes-abstract classes-access-control-derived

classes-abstract: classes-abstract.cpp
	g++ classes-abstract.cpp -o classes-abstract

classes-access-control: classes-access-control.cpp
	g++ classes-access-control.cpp -o classes-access-control

classes-access-control-derived: classes-access-control-derived.cpp
	g++ classes-access-control-derived.cpp -o classes-access-control-derived
	
classes-final: classes-final.cpp
	g++ classes-final.cpp -o classes-final
	
classes-inner: classes-inner.cpp
	g++ classes-inner.cpp -o classes-inner
	
classes-polymorphism: classes-polymorphism.cpp
	g++ classes-polymorphism.cpp -o classes-polymorphism

classes-super-this: classes-super-this.cpp
	g++ classes-super-this.cpp -o classes-super-this
	
clean:
	rm -f *.o
