all: classes-abstract classes-access-control-derived

classes-access-control-derived: classes-access-control-derived.cpp
	g++ classes-access-control-derived.cpp -o classes-access-control-derived

classes-abstract: classes-abstract.cpp
	g++ classes-abstract.cpp -o classes-abstract
	
clean:
	rm -f *.o
